---
title: "Microarray Data Stomach Antrum Epithelia, Lgr4 KO - DGE Reanalysis with LIMMA"
author: "Hilmar Berger"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---

```{r, echo=FALSE, results='hide', messages=FALSE}
rm(list=ls())
suppressMessages(library(limma))
suppressMessages(library(pheatmap))
library(xtable)
library(reshape2)
library(writexl)

load("../Data/Preprocessed/Stomach_antrum_Lgr4_KO_preprocessed_data.Rdata")
ed$Cy3_group = paste(ed$Cy3, ed$Experiment, sep="_")
ed$Cy5_group = paste(ed$Cy5, ed$Experiment, sep="_")

result_folder = "../Results"
if (!file.exists(result_folder)) dir.create(result_folder, recursive=T)

```

# Introduction

This document describes preprocessing and QC of mouse experiments (stomach Antrum +/- Lgr4 KO) hybridized as dual channel to Agilent 014868 micro array. 

# DGE

We here use standard two-channel analysis of the microarray data and compare:  

  - Lgr4 KO vs. Lgr4 WT (both Hp infected)

```{r}
all_results = list()
```


```{r}
controls = MA$genes$ControlType!=0

MA.avg <- avereps(MA[!controls,], ID=MA[!controls,]$genes$ProbeName)

dswp = ifelse(ed$Cy5_treatment %in% c("Lgr4 KO"), FALSE, TRUE)
cy3_label = ed$Cy3
cy5_label = ed$Cy5
scan_id = ed$Chip.Barcode
ed$array_label = paste(ifelse(dswp, cy3_label, cy5_label), "_",ifelse(dswp,cy5_label, cy3_label),"_",dswp,"_",ed$Scan.ID,sep="")


###################################
# Lgr4 KO vs. WT
###################################

sel_samples = rownames(subset(ed, Cy5_treatment %in% c("Lgr4 KO","control")))
ed_tmp = ed[sel_samples,]
design = ifelse(ed_tmp$Cy5_treatment=="Lgr4 KO", 1, -1)
fit <- lmFit(MA.avg[,sel_samples], design)
fit <- eBayes(fit)
res = topTable(fit, adjust = "BH",number=nrow(fit), confint = T)
ratio_tab = sweep(MA.avg[,sel_samples]$M, 2, design, "*")
colnames(ratio_tab) = ed_tmp$array_label
res = merge(res, ratio_tab, all.x=T, by.x="ProbeName", by.y=0, sort=F)
all_results[["Lgr4_KO_vs_control"]] = res

common_colnames = colnames(topTable(fit, adjust = "BH",number=nrow(fit)))
```

## Volcano plot

```{r, volcano, echo=FALSE, fig.width=8, fig.height=6}
all_target_conditions = names(all_results)
par(mfrow=c(1,1), mar=c(4,4,4,2))

for (tc in all_target_conditions) {
  r = all_results[[tc]]
  plot(r$logFC, -log10(r$adj.P.Val),xlab="log2 Fold Change",ylab="-log10(adj. p-val)", ylim=c(0,max(2,max(-log10(r$adj.P.Val),na.rm=T))))
  title(main=tc, sub=paste("(",nrow(subset(r, adj.P.Val < 0.05))," signif. DE genes)",sep="") )
  abline(h=-log10(0.05),col="red")
  abline(v=c(-1,1))
}

for (tc in all_target_conditions) {
  r = all_results[[tc]]
  plot(r$logFC, -log10(r$P.Value),xlab="log2 Fold Change",ylab="-log10(raw. p-val)", ylim=c(0,max(2,max(-log10(r$P.Value),na.rm=T))))
  title(main=tc, sub=paste("(",nrow(subset(r, P.Value < 0.05))," signif. DE genes)",sep="") )
  abline(h=-log10(0.05),col="red")
  abline(v=c(-1,1))
}
```

# Data export 

All result files are exported to `r result_folder`.


```{r, write_tabs, echo=FALSE}
output_file_prefix = paste(result_folder,"Differential_expression_results_", sep="/")
selected_cols = c("ProbeName", "GeneSymbol", "GeneName","EntrezID","GeneSymbol_Gencode","GencodeM12MappingStatus","Transcript_Type","logFC","AveExpr","t","P.Value","adj.P.Val" )

for (tc in all_target_conditions) {
  #write.table(all_results[[tc]][,selected_cols], file=paste(output_file_prefix, tc, ".txt", sep="" ), row.names=F , sep="\t", dec=".")
  write.table(all_results[[tc]], file=paste(output_file_prefix, tc, ".txt", sep="" ), row.names=F , sep="\t", dec=".")
}

short_names = list()
for (i in names(all_results)) {
  ii = gsub(" ","_", gsub(",","_",i))
  short_names[[i]] = ii
}

DGE_Excel_filename = file.path(result_folder,"DiffExpression_all_results.xlsx")
write_xlsx(all_results, path=DGE_Excel_filename)

```


```{r}
filename = paste(result_folder,"DGE_results.Rdata",sep="/")
exp_design = ed
save(all_results, exp_design, MA,file=filename)
```


# Session Info
```{r}
sessionInfo()
```